hideType = "RELOADING"
rgbProgress = false
forceClose = false
showIn = "ALL"
type = "PROGRESS"
reloadText = "Edit in config!"
resetResources = false
reInitScreen = true
earlyPackStatusSend = true
animationSpeed = 500.0
aprilFool = "DISABLED"
